### PR TITLE
Typescript bindings

### PR DESCRIPTION
**Pull request by euforic**
- Add typescript contract binding generation
- Update package.json with generation script
- Update package.json to use local bins to ensure consistent versions
- Add .eslintignore to ignore generated typescript code
- Bump Node.js / NPM version
- Update travis Node.js version

This one might not be as needed, but I figured it would be nice to have an official js API binding too

**Note**
Please merge #74 -> #73 and then this PR

### CODE REVIEW

**Comment by jcvernaleo** [comment]
Big +1 on making sure you use local bins in package.json.  I have no opinion on the typescript stuff itself.

Not sure about bumping the allowed nodejs version.  @gabmontes should probably comment on that.

**Comment by euforic** [comment]
@jcvernaleo yeah in order to get the typescript bindings to generate I had to bump the version of node. You can diff the compile with the two different versions of node I'm pretty sure they are identical.

**Comment by jcvernaleo** [comment]
It occurs to me that if you need a newer nodejs maybe it should also be updated in the `.travis.yml` as well.

**Comment by euforic** [comment]
@jcvernaleo updated travis and commit notes

**Pull request closed without merging**
