### PR TITLE
Removed duplicate code from multiSubwithdraw  

### PR DESCRIPTION
**Pull request by rokso**
Fixed number 10 and 14 from issue #40

1. Use address array instead of uint array
2. Changed subwithdrawFor to use if condition instead of require checks
3. Removed duplicate code from multiSubwithdrawFor
4. Updated test according to removal of require check
5. Update timed-test to use shared time travel util

### CODE REVIEW

**Comment by rokso** [comment]
@filcap @patidarmanoj10  Please review the changes.

**Comment by patidarmanoj10** [comment]
LGTM

**Comment by rokso** [comment]
@filcap @patidarmanoj10 right now multiSubwithdraw is using the subwithdraw function and failing subwithdraw will fail multiSubwithdraw. I think we can directly call subwithdrawFor from multiSubwithdraw and allow subwithdraw to have a require check. This will solve the both issue.

**Comment by rokso** [comment]
@patidarmanoj10 @filcap I have fixed it as suggested. I have also tried to fix proceeds.js test which happens to fail on Travis from time to time.

**Pull request merged**
